### PR TITLE
Add support for RoseStacker

### PR DESCRIPTION
**Pull request by NicoNekoDev**
No one likes competition, but some people might need support for it!
Link to it: https://www.spigotmc.org/resources/rosestacker.82729/

### CODE REVIEW

**Comment by briannastatic** [comment]
We support stacking plugins through SongodaCore. I suggest you make the PR for that repo.

**Comment by NicoNekoDev** [comment]
> We support stacking plugins through SongodaCore. I suggest you make the PR for that repo.

Then this part of EpicHoppers should have been migrated to use the SongodaCore.

**Comment by briannastatic** [comment]
Yeah, you're right. I didn't look at the code I just figured this was straightforward. My sincerest apologies for my mistake. This is probably acceptable in that case although this code should really be in core. I'm sure Sprax will help you out shortly whether he wants to put this in core or as you have it.

**Comment by NicoNekoDev** [comment]
> Yeah, you're right. I didn't look at the code I just figured this was straightforward. My sincerest apologies for my mistake. This is probably acceptable in that case although this code should really be in core. I'm sure Sprax will help you out shortly whether he wants to put this in core or as you have it.

It's okay, I'm gonna do a PR for core and close this PR. I already looked at how core implements stacking plugins and I think is much better that way.

**Pull request closed without merging**
