### PR TITLE
Update ModuleBlockBreak.java

### PR DESCRIPTION
**Pull request by Euphillya**
Fix a bug with PaperMC, if we destroy with hopper, he dont drop item.

### CODE REVIEW

**Comment by brasilcraft54** [comment]
you have to forbid even reporting problems because this plugin is full of problems with no support for rosestacker, no support for superiorskyblock full of bugs and problems to buy this is a waste of time besides you take months to update the plugin or respond on the site.

**Comment by briannastatic** [comment]
This commit was merged a long time ago. Message Brianna#0001 on Discord if you need further assistance.

**Comment by brasilcraft54** [comment]
> This commit was merged a long time ago. Message Brianna#1 on Discord if you need further assistance.

I have already sent in your support other people also sent and nobody answers you are a joke

**Comment by briannastatic** [comment]
I've been recovering from major surgery for a little over a month now. I haven't been around to help and even if I tried the pain medication would inhibit my efforts. I'm able to help you now if you just message me on Discord. There are three zeros before the one in my discord handle.

**Comment by brasilcraft54** [comment]
> I've been recovering from major surgery for a little over a month now. I haven't been around to help and even if I tried the pain medication would inhibit my efforts. I'm able to help you now if you just message me on Discord. There are three zeros before the one in my discord handle.

https://feedback.songoda.com/d/1160-epichoppers-and-hopper-limit-with-superiorskyblock2

**Comment by briannastatic** [comment]
That's not the right place to put that request.

**Comment by brasilcraft54** [comment]
> Esse não é o lugar certo para fazer esse pedido.

https://feedback.songoda.com/t/epichoppers   

This is the biggest proof that you don't support anyone.

**Comment by briannastatic** [comment]
That's not a support site, what are you talking about? That is a forum for feedback, we don't support people there it's not how it works.

**Comment by briannastatic** [comment]
Those people are leaving SUGGESTIONS. That's what it's for, to suggest new ideas or alterations. Not for support.

**Comment by brasilcraft54** [comment]
> That's not a support site, what are you talking about? That is a forum for feedback, we don't support people there it's not how it works.

I just want to let it on record so that no one makes the same mistake as me in buying this plugin that takes months to be updated you have no support on your site and this plugin does not support rosestacker and superiorskyblock

**Comment by brasilcraft54** [comment]
> Those people are leaving SUGGESTIONS. That's what it's for, to suggest new ideas or alterations. Not for support.

and did you answer any suggestions? look there, don't even want to answer

**Comment by briannastatic** [comment]
No, we don't answer them. We don't have the resources. When we add a suggestion to the plugin if we do we close the suggestion. No one is paid here, we're all volunteers.

**Comment by brasilcraft54** [comment]
adding support for superiorskyblock and rosestacker is difficult?

**Comment by briannastatic** [comment]
I have no idea, you would have to ask a developer on our team.

**Comment by brasilcraft54** [comment]
I already asked and was told to add it to the suggestions but when I saw that it has been around since June no one answered or added it, I didn't waste my time.

https://feedback.songoda.com/d/1160-epichoppers-and-hopper-limit-with-superiorskyblock2

**Comment by briannastatic** [comment]
I guess they don't have time then. I believe they're all busy with school and hardly able to keep up with bug reports alone. So I don't blame them for not having time to add new features.

**Comment by brasilcraft54** [comment]
> I guess they don't have time then. I believe they're all busy with school and hardly able to keep up with bug reports alone. So I don't blame them for not having time to add new features.

so if you don't have time add for free don't be making money on people and not on support.

**Comment by briannastatic** [comment]
They are free, you can compile them yourself on GitHub. The money goes towards our servers and websites to keep them online.

**Pull request merged**
